### PR TITLE
Add a logo for scale-ci

### PR DESCRIPTION
**Pull request by chaitanyaenr**
Thanks to Mary Shakshober for designing the logo.

### CODE REVIEW

**Comment by sjug** [comment]
Given my utter lack of graphics design ability, I don't love it but am in no position to do anything better so if it makes you happy. :+1:

**Comment by jmencak** [comment]
LGTM

**Comment by ashishkamra** [comment]
Its nice. gears inside a cloud.

**Comment by chaitanyaenr** [comment]
Any thoughts or suggestions?

**Comment by chaitanyaenr** [comment]
Thanks for the reviews, @akrzos can we merge this?

**Comment by akrzos** [comment]
Wegot a new logo right?  Can we get that posted in here?  Thanks!

**Comment by maryshak1996** [comment]
@chaitanyaenr @akrzos  I tried to open another PR with the three color variants but some permissions stopped that. Posting them here instead! 
[Logo-formats.zip](https://github.com/openshift-scale/scale-ci-pipeline/files/3322579/Logo-formats.zip)

**Comment by akrzos** [comment]
> @chaitanyaenr @akrzos I tried to open another PR with the three color variants but some permissions stopped that. Posting them here instead!
> [Logo-formats.zip](https://github.com/openshift-scale/scale-ci-pipeline/files/3322579/Logo-formats.zip)

Hi Mary,

Thanks for the logos. It is interesting that Github wouldn't allow you to create a pull request from outside the organization?  Is there something I need to open up in the permissions?  If not I can help you with forking and creating a p/r with the logos.

**Comment by chaitanyaenr** [comment]
Mary, thanks for designing the logos again! Let Alex or I know if adding you as a collaborator to the repository helps in creating a PR to add the logo.

**Comment by maryshak1996** [comment]
@akrzos @chaitanyaenr ya I'm not real sure what the issue is (I've never had this problem before with other repos). The error message that I am being fed is "Authentication failed. You may not have permission to access the repository or the repository may have been archived."

**Comment by akrzos** [comment]
> @akrzos @chaitanyaenr ya I'm not real sure what the issue is (I've never had this problem before with other repos). The error message that I am being fed is "Authentication failed. You may not have permission to access the repository or the repository may have been archived."

Check your remotes on your local pull of the repo.  

Example:
```
$ git remote -v
origin	git@github.com:akrzos/scale-ci-pipeline.git (fetch)
origin	git@github.com:akrzos/scale-ci-pipeline.git (push)
upstream	https://github.com/openshift-scale/scale-ci-pipeline.git (fetch)
upstream	https://github.com/openshift-scale/scale-ci-pipeline.git (push)
```

I am not sure you have the correct one forked as it only looks like myself and Ravi have this repo forked (See https://github.com/openshift-scale/scale-ci-pipeline/network/members)

**Comment by chaitanyaenr** [comment]
@maryshak1996 cloning the repo using SSH might have some issues sometimes when using github desktop, can we try cloning using HTTPS and see if it works. Not sure if this the problem though.

**Comment by maryshak1996** [comment]
@chaitanyaenr @alex my coworkers and I tried to troubleshoot this for a while (including trying what you have suggested above) but are not having any luck. For the sake of time, could you merge this in from your end, either with the zip that I added or from here: https://github.com/maryshak1996/scale-ci-pipeline/blob/master/images/Logo-formats.zip ?

**Comment by chaitanyaenr** [comment]
@maryshak1996 sure, updated the PR with the logo. PTAL and let us know if any changes are needed. Thanks.

**Comment by chaitanyaenr** [comment]
@akrzos yes, we can merge this I guess since we got a thumbs up from Mary.

**Comment by maryshak1996** [comment]
let me know if there's anything else that you need from me!

**Pull request merged**
