### PR TITLE
Refactor scale-ci-pipeline

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This commit:
- Reduces the number of vars to define by passing the properties
  file without verifying. Adding a new workload or modifying an
  existing workload no longer requires adding vars. Inspired from
  https://github.com/openshift-scale/scale-ci-pipeline/tree/v0.1.
- Enables to use a single build script for all the workloads. This
  would make it easy for on-boarding a new workload as the user just
  needs to submit a JJB template and a sample properties file.

### CODE REVIEW

**Comment by mohit-sheth** [comment]
Hi ravi, did you get a chance to test it out once?

**Comment by chaitanyaenr** [comment]
@mohit-sheth Yes, tested a couple of jobs.

**Review by mohit-sheth — APPROVED** [review]
LGTM, awesome work!!
@chaitanyaenr++

**Review by whitleykeith — APPROVED** [review]
LGTM!

**Pull request merged**
